"""Tests for randomized domain generator (Issue #59)."""

from __future__ import annotations

import pytest
import numpy as np
from admesh_domains.generator import random_domain, _generate_rectangle_boundary


class TestRandomDomainBasic:
    """Tests for random_domain API."""

    def test_random_domain_triangle_basic(self):
        """Generate basic triangle mesh."""
        domain, fort14_bytes = random_domain(seed=42, node_count=50)

        assert isinstance(domain, dict)
        assert "name" in domain
        assert "element_type" in domain
        assert domain["element_type"] == "triangle"
        assert isinstance(fort14_bytes, bytes)
        assert len(fort14_bytes) > 0

    def test_random_domain_deterministic(self):
        """Same seed produces byte-identical output."""
        _, bytes1 = random_domain(seed=42, node_count=100)
        _, bytes2 = random_domain(seed=42, node_count=100)

        assert bytes1 == bytes2

    def test_random_domain_different_seeds_differ(self):
        """Different seeds produce different meshes."""
        _, bytes1 = random_domain(seed=42, node_count=100)
        _, bytes2 = random_domain(seed=43, node_count=100)

        assert bytes1 != bytes2

    def test_random_domain_quad(self):
        """Generate quad mesh."""
        domain, fort14_bytes = random_domain(
            seed=42, element_type="quad", node_count=50
        )

        assert domain["element_type"] == "quad"
        assert len(fort14_bytes) > 0

    def test_random_domain_mixed(self):
        """Generate mixed-element mesh (MVP: mostly triangles)."""
        domain, fort14_bytes = random_domain(
            seed=42, element_type="mixed", node_count=50
        )

        assert domain["element_type"] == "mixed"
        assert len(fort14_bytes) > 0

    def test_random_domain_invalid_shape(self):
        """Reject unsupported shapes."""
        with pytest.raises(ValueError, match="shape"):
            random_domain(seed=42, shape="circle", node_count=50)

    def test_random_domain_invalid_element_type(self):
        """Reject invalid element types."""
        with pytest.raises(ValueError, match="element_type"):
            random_domain(seed=42, element_type="hexagon", node_count=50)

    def test_random_domain_too_few_nodes(self):
        """Reject node_count < 3."""
        with pytest.raises(ValueError, match="node_count"):
            random_domain(seed=42, node_count=2)

    def test_random_domain_fort14_format(self):
        """Generated bytes are valid fort.14 format."""
        _, fort14_bytes = random_domain(seed=42, node_count=50)
        fort14_str = fort14_bytes.decode("utf-8")

        # Check structure: header, element count line, vertices, elements, boundaries
        lines = fort14_str.strip().split("\n")
        assert len(lines) > 5

        # Second line should be element count and vertex count
        header_line = lines[1].split()
        assert len(header_line) >= 2
        n_elems = int(header_line[0])
        n_verts = int(header_line[1])
        assert n_elems > 0
        assert n_verts > 0

    def test_random_domain_metadata(self):
        """Metadata includes required fields."""
        domain, _ = random_domain(seed=42, node_count=100)

        assert domain["node_count"] > 0
        assert domain["element_count"] > 0
        assert domain["shape"] == "rectangle"


class TestRectangleBoundary:
    """Tests for rectangle boundary generation."""

    def test_rectangle_boundary_corners(self):
        """Verify corners are included."""
        rng = np.random.RandomState(42)
        points, boundary_edges = _generate_rectangle_boundary(node_count=100, rng=rng)

        # Check corners exist
        corners = np.array([[0, 0], [1, 0], [1, 1], [0, 1]])
        for corner in corners:
            found = np.any(np.all(points == corner, axis=1))
            assert found, f"Corner {corner} not found in points"

    def test_rectangle_boundary_count(self):
        """Verify point count is close to requested."""
        rng = np.random.RandomState(42)
        node_count = 100
        points, _ = _generate_rectangle_boundary(node_count=node_count, rng=rng)

        # Should be within 10% of target
        assert 90 <= len(points) <= 110

    def test_rectangle_boundary_in_unit_square(self):
        """All points are in [0, 1]²."""
        rng = np.random.RandomState(42)
        points, _ = _generate_rectangle_boundary(node_count=200, rng=rng)

        assert np.all(points[:, 0] >= 0)
        assert np.all(points[:, 0] <= 1)
        assert np.all(points[:, 1] >= 0)
        assert np.all(points[:, 1] <= 1)

    def test_rectangle_boundary_edges_form_loop(self):
        """Boundary edges form a closed loop."""
        rng = np.random.RandomState(42)
        _, boundary_edges = _generate_rectangle_boundary(node_count=100, rng=rng)

        # Each vertex should appear exactly 2 times in edges (in/out degree 1)
        n_boundary = len(np.unique(boundary_edges.flatten()))
        assert n_boundary == len(boundary_edges)


class TestFort14Output:
    """Tests for fort.14 format output."""

    def test_fort14_is_decodable(self):
        """Generated fort14 bytes are valid UTF-8."""
        _, fort14_bytes = random_domain(seed=42, node_count=50)

        fort14_str = fort14_bytes.decode("utf-8")
        assert len(fort14_str) > 0

    def test_fort14_contains_vertices(self):
        """Generated fort14 includes vertex coordinates."""
        _, fort14_bytes = random_domain(seed=42, node_count=100)
        fort14_str = fort14_bytes.decode("utf-8")

        lines = fort14_str.strip().split("\n")
        header_line = lines[1].split()
        n_verts = int(header_line[1])

        # Should have header + element count line + vertices + elements + boundaries
        assert len(lines) >= 2 + n_verts + 2

    def test_fort14_contains_elements(self):
        """Generated fort14 includes element connectivity."""
        _, fort14_bytes = random_domain(seed=42, node_count=100)
        fort14_str = fort14_bytes.decode("utf-8")

        # Element lines look like "<id> <3-or-4> <v0> <v1> <v2>[ <v3>]".
        # Whitespace is implementation-defined, so check structurally.
        found_elem_line = False
        for line in fort14_str.splitlines():
            toks = line.split()
            if len(toks) in (5, 6) and toks[1] in ("3", "4"):
                try:
                    [int(t) for t in toks]
                    found_elem_line = True
                    break
                except ValueError:
                    continue
        assert found_elem_line, "no fort.14 element line found"
